<li class="item"> <a href="[field:arcurl/]" title="">
        <h2 class="caseList_title">[field:title/]</h2>
        <p class="caseList_brand">[field:typename/]</p>
        <p class="caseList_img"><img src="[field:picname/]" width="254" alt=""></p>
        </a>
        <div class="caseList_about"> </div>
        <a href="[field:arcurl/]" title="[field:title/]" class="caseList_more">READ MORE</a> </li>