<?php
$z[0]=Array("channel"," <a href=\"[field:typeurl/]\" title=\"\">[field:typename/]</a>  | \r\n      ",90,212);
$z[0][4]['type']="top";
$z[0][4]['row']="10";
$z[1]=Array("global","",323,349);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("global","",379,400);
$z[2][4]['name']="cfg_dz";
$z[3]=Array("global","",430,452);
$z[3][4]['name']="cfg_tel";
$z[4]=Array("global","",1177,1201);
$z[4][4]['name']="cfg_beian";

?>