<?php
$z[0]=Array("field","",66,85);
$z[0][4]['name']="title";
$z[1]=Array("global","",86,112);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",153,182);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",222,280);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",786,821);
$z[4][4]['filename']="head.htm";
$z[5]=Array("channel","\r\n        <li> <a href=\"[field:typeurl/]\"><span>[field:typename/]</span></a> </li>\r\n        ",1263,1522);
$z[5][4]['type']="son";
$z[5][4]['currentstyle']="<li class='current'><a href='~typelink~' class='thisclass'><span>~typename~</span></a></li>";
$z[6]=Array("list","\r\n      <li class=\"item\"> <a href=\"[field:arcurl/]\" title=\"\">\r\n        <h2 class=\"caseList_title\">[field:title/]</h2>\r\n        <p class=\"caseList_brand\">[field:typename/]</p>\r\n        <p class=\"caseList_img\"><img src=\"[field:picname/]\" width=\"254\" alt=\"\"></p>\r\n        </a>\r\n        <div class=\"caseList_about\"> </div>\r\n        <a href=\"[field:arcurl/]\" title=\"[field:title/]\" class=\"caseList_more\">READ MORE</a> </li>\r\n      ",1664,2127);
$z[6][4]['pagesize']="16";
$z[7]=Array("include","",2553,2590);
$z[7][4]['filename']="footer.htm";

?>