<?php
$z[0]=Array("field","",66,85);
$z[0][4]['name']="title";
$z[1]=Array("global","",86,112);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",153,182);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",222,280);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",786,821);
$z[4][4]['filename']="head.htm";
$z[5]=Array("list","\r\n    <li><img src=\"[field:picname/]\" alt=\"\" /></li>\r\n    ",1254,1349);
$z[5][4]['pagesize']="15";
$z[6]=Array("include","",1417,1454);
$z[6][4]['filename']="footer.htm";

?>