<?php
$z[0]=Array("field","",66,85);
$z[0][4]['name']="title";
$z[1]=Array("global","",86,112);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",153,182);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",222,280);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",786,821);
$z[4][4]['filename']="head.htm";
$z[5]=Array("field","",2617,2638);
$z[5][4]['name']="content";
$z[6]=Array("include","",2863,2900);
$z[6][4]['filename']="footer.htm";

?>